### ISSUE TITLE
Binding Issues

### ISSUE THREAD

**Issue by john-attrium-204** [corymickelson/NoPoDoFo#92]
Hey Cory!
Thanks for the great library.

**I am facing **issue** of binding to shared object file.**
Following is the log printed on my console

Error: libssl.so.1.1: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:730:18)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at bindings (/var/www/html/integra/apis/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/var/www/html/integra/apis/node_modules/nopodofo/index.js:1:101)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)

Please suggest best possible way to fix it.

Thanks in advance

**Comment by corymickelson** [comment]
@john-attrium-204 this error is stating that the ssl (openssl 1.1) is not found. Please ensure youve installed openssl. What OS are you on?
